name: Update versions

on: [push]

jobs:
  setup-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    env:
      BUMP_TYPE: ${{ github.event.ref == 'refs/heads/develop' && 'minor' || 'patch' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install git
        python -m pip install -r dev_requirements.txt
  build:
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/main
          fetch-depth: 0
      - name: Bump version and build
        run: |
          export BUMP_TYPE=${BUMP_TYPE:-patch}
          python -m updater
          git add extensions/sources/*
          git add sources.json
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Bump version"
          git push
      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output
      - name: Upload new sources.json
        uses: actions/upload-artifact@v4
        with:
          name: build-output-sources-json
          path: sources.json
  commit-and-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: refs/heads/repo
    - name: Download workspace
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: output_new
    - name: Download sources.json
      uses: actions/download-artifact@v4
      with:
        name: build-output-sources-json
        path: .
    - name: Set up Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
    - name: Copy files
      run: |
          echo "Copying files"
          ls -la output_new
          mkdir -p output
          ls -la output
          cp -rf output_new/* output/
    - name: Commit and push changes
      run: |
        git add output/*
        git add sources.json
        git commit -m "Commit updated zip files and sources.json"
        git push origin HEAD:refs/heads/repo